application: cpppaste
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css
  
- url: /codes
  static_dir: codes

- url: /submit
  script: submit.py
  
- url: /code/.*
  script: main.py
  
- url: /getentry
  script: main.py
  
- url: /.*
  script: main.py